GET http://localhost:5001/api/blogs

###

POST http://localhost:5001/api/blogs
Content-Type: application/json

{
    "title": "First class tests",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
    "likes": 10,
     "userId": "5a422b891b54a676234d17fa"
  }

###

PUT http://localhost:5001/api/blogs/619248f92210d5f2d7826948
Content-Type: application/json

 {
   "title": "iyanda",
  "author": "Alaweda",
  "url": "igotoskul.com",
  "likes": 9,
  "id": "619248f92210d5f2d7826948"
}

###
     

DELETE http://localhost:5001/api/blogs/619ea312a5ed046dddf21726