GET http://localhost:5001/api/blogs

###

POST http://localhost:5001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthbWlsYSIsImlkIjoiNjFlODE5NDEzMmZiMzI4ZjFjOWFhODZmIiwiaWF0IjoxNjQyNjE2NjEyLCJleHAiOjE2NDI2MjAyMTJ9.x3QFV-7Sdlyktm-50HFfeO1eWcCk5Hf6xYNPrefQ2hs

{
    "title": "First classs",
    "author": "Matti Luukkainen",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
    "likes": 10
  }

###

PUT http://localhost:5001/api/blogs/619248f92210d5f2d7826948
Content-Type: application/json

 {
   "title": "iyanda",
  "author": "Alaweda",
  "url": "igotoskul.com",
  "likes": 9,
  "id": "619248f92210d5f2d7826948"
}

###
     

DELETE http://localhost:5001/api/blogs/619ea312a5ed046dddf21726