
GET http://localhost:5001/api/users

###

POST http://localhost:5001/api/users
Content-Type: application/json

{
    "blogs": [],
    "username": "ade",
    "name": "adekunle",
    "password": "aweda"
  }