GET http://localhost:5001/api/blogs

###
POST http://localhost:5001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2Fzb3phIiwiaWQiOiI2MWY3ZGYzMGM2YTA5OWNlZjVmNzk1YjAiLCJpYXQiOjE2NDM2MzQ0OTQsImV4cCI6MTY0MzYzODA5NH0.c4a9-DXhTRbxvWdoLeullJQUOVXzZBfTGSMRdzsK6Xw

{
    "title": "First classs",
    "author": "Matti Luukkainen",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
    "likes": 10
  }

###

PUT http://localhost:5001/api/blogs/619248f92210d5f2d7826948
Content-Type: application/json

 {
   "title": "iyanda",
  "author": "Alaweda",
  "url": "igotoskul.com",
  "likes": 9,
  "id": "619248f92210d5f2d7826948"
}

###
     

DELETE http://localhost:5001/api/blogs/61f7a3b953fbf407127858ef
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2Fzb3phIiwiaWQiOiI2MWY2ZmI4YjMxMTA5NzJiZjZkN2RlYzUiLCJpYXQiOjE2NDM2MTg3MzUsImV4cCI6MTY0MzYyMjMzNX0.Lg1jCYKLs7kDrsxVwrmsDAesmoE_DzlJzKQtqG_2sgM